CaptionLive/CaptionLive

.gitignore
api/pom.xml
api/src/main/java/com/aguri/captionlive/CaptionliveApplication.java
api/src/main/java/com/aguri/captionlive/common/exception/UserNotFoundException.java
api/src/main/java/com/aguri/captionlive/controller/UserController.java
api/src/main/java/com/aguri/captionlive/model/Glossary.java
api/src/main/java/com/aguri/captionlive/model/Membership.java
api/src/main/java/com/aguri/captionlive/model/Organization.java
api/src/main/java/com/aguri/captionlive/model/Ownership.java
api/src/main/java/com/aguri/captionlive/model/Project.java
api/src/main/java/com/aguri/captionlive/model/Segment.java
api/src/main/java/com/aguri/captionlive/model/Task.java
api/src/main/java/com/aguri/captionlive/model/User.java
api/src/main/java/com/aguri/captionlive/repository/UserRepository.java
api/src/main/java/com/aguri/captionlive/service/UserService.java
api/src/main/java/com/aguri/captionlive/service/impl/UserServiceImpl.java
api/src/main/resources/application.yml
api/src/test/java/com/aguri/captionlive/CaptionliveApplicationTests.java
docker-compose/.gitignore

- initialize database and project framework
- The project uses JPA to initialize the database with models, and is built using Spring Boot.
- add simple user CRUD code to verify success

initialize database and project framework

---

api/src/main/java/com/aguri/captionlive/model/Glossary.java
api/src/main/java/com/aguri/captionlive/model/Membership.java
api/src/main/java/com/aguri/captionlive/model/Organization.java
api/src/main/java/com/aguri/captionlive/model/Ownership.java
api/src/main/java/com/aguri/captionlive/model/Project.java
api/src/main/java/com/aguri/captionlive/model/Segment.java
api/src/main/java/com/aguri/captionlive/model/Task.java
api/src/main/java/com/aguri/captionlive/model/User.java
api/src/main/resources/application.yml

- [issue 8](https://github.com/lijiaxi2018/CaptionLive/issues/8)
- including the "lastUpdatedTime" and "createdTime" columns in every table of DB.
- formatting TimeData Type (Java: LocalDateTime, PSQL: timestamp).

issue 8:decide necessary timestamp for database tables

---

.github/workflows/docker-push.yml

- #7 
- Added an GitHub Action where, when codes are pushed into the main branch, it builds images and push images to the DockerHub

issue7: added CI/CD pipeline to push images to DockerHub

---

api/src/main/resources/application.yml

- #7 
- Test if CICD pipeline works as expected

issue7: test CICD pipeline

---

api/README.md
docker-compose/docker-compose.yml
frontend/DockerFile
frontend/README.md

- No DockerFile for Frontend
- Added DockerFile for Frontend
- Modified README

<feature: frontend Docker-file; modified README>

---

.github/workflows/docker-build-frontend.yml

- Needs CICD for Frontend
- Added Image Build Workflow for Frontend when a new PR is made towards the main branch

<feature: frontend CICD workflow>

---

.github/workflows/docker-push-frontend.yml

- Needs CICD for Frontend
- Added Image Push Workflow for Frontend when a new PR is pushed to the main branch

<feature: frontend push CICD workflow>

---

api/src/main/resources/application.yml
frontend/src/pages/MyHome.js

- Need to test CICD pipelines
- Slightly modified two files in Frontend and Api respectively

<feature: Test CICD pipeline;>

---

api/src/main/java/com/aguri/captionlive/DTO/UserInfoResponse.java
api/src/main/java/com/aguri/captionlive/controller/OrganizationController.java
api/src/main/java/com/aguri/captionlive/controller/ProjectController.java
api/src/main/java/com/aguri/captionlive/controller/UserController.java
api/src/main/java/com/aguri/captionlive/model/Membership.java
api/src/main/java/com/aguri/captionlive/model/Organization.java
api/src/main/java/com/aguri/captionlive/model/Ownership.java
api/src/main/java/com/aguri/captionlive/model/Project.java
api/src/main/java/com/aguri/captionlive/model/Segment.java
api/src/main/java/com/aguri/captionlive/model/User.java
api/src/main/java/com/aguri/captionlive/repository/MembershipRepository.java
api/src/main/java/com/aguri/captionlive/repository/OrganizationRepository.java
api/src/main/java/com/aguri/captionlive/repository/OwnershipRepository.java
api/src/main/java/com/aguri/captionlive/repository/ProjectRepository.java
api/src/main/java/com/aguri/captionlive/repository/SegmentRepository.java
api/src/main/java/com/aguri/captionlive/service/FileRecordService.java
api/src/main/java/com/aguri/captionlive/service/OrganizationService.java
api/src/main/java/com/aguri/captionlive/service/ProjectService.java
api/src/main/java/com/aguri/captionlive/service/UserService.java
api/src/main/java/com/aguri/captionlive/service/impl/FileRecordServiceImpl.java
api/src/main/java/com/aguri/captionlive/service/impl/OrganizationServiceImpl.java
api/src/main/java/com/aguri/captionlive/service/impl/ProjectServiceImpl.java
api/src/main/java/com/aguri/captionlive/service/impl/SegmentServiceImpl.java
api/src/main/java/com/aguri/captionlive/service/impl/TaskServiceImpl.java
api/src/main/java/com/aguri/captionlive/service/impl/UserServiceImpl.java

- database pk 
- update api and  add new api

api update and add database pk

---

api/src/main/java/com/aguri/captionlive/model/Access.java
api/src/main/java/com/aguri/captionlive/model/Glossary.java
api/src/main/java/com/aguri/captionlive/model/Project.java
api/src/main/java/com/aguri/captionlive/model/User.java
api/src/main/java/com/aguri/captionlive/repository/AccessRepository.java
api/src/main/java/com/aguri/captionlive/repository/ProjectRepository.java
api/src/main/java/com/aguri/captionlive/service/UserService.java
api/src/main/java/com/aguri/captionlive/service/impl/AccessServiceImpl.java
api/src/main/java/com/aguri/captionlive/service/impl/ProjectServiceImpl.java
api/src/main/java/com/aguri/captionlive/service/impl/UserServiceImpl.java

- database miss some fk in db
- add fk in db
- update some code to adapt new  fk

Feature/no ref/add database fk

---

api/src/main/java/com/aguri/captionlive/DTO/ProjectInfo.java
api/src/main/java/com/aguri/captionlive/common/exception/GlobalExceptionHandler.java
api/src/main/java/com/aguri/captionlive/controller/OrganizationController.java
api/src/main/java/com/aguri/captionlive/controller/ProjectController.java
api/src/main/java/com/aguri/captionlive/controller/TaskController.java
api/src/main/java/com/aguri/captionlive/model/Project.java
api/src/main/java/com/aguri/captionlive/model/Segment.java
api/src/main/java/com/aguri/captionlive/model/Task.java
api/src/main/java/com/aguri/captionlive/repository/ProjectRepository.java
api/src/main/java/com/aguri/captionlive/service/OrganizationService.java
api/src/main/java/com/aguri/captionlive/service/impl/OrganizationServiceImpl.java

- Now supports paginated querying of projects under an organization.

Paginated Querying Of Projects Under An Organization

---

api/src/main/java/com/aguri/captionlive/config/CorsConfig.java

<feat: add cors>

---

frontend/README.md
frontend/src/App.css
frontend/src/pages/MyHome/MyHome.js
frontend/src/redux/store.js
frontend/src/services/user.js

- Want to call API provided by the backend
- Added CURD for users via RTK query
- Slightly modified Frontend README
- Slightly modified App.css

<feature: Frontend added basic rtk query for users;>

---

api/src/main/java/com/aguri/captionlive/model/User.java

- Username is the only credential to identify the user, it should be set to unique.
- just do it

<fix: username should be unique>

---

api/src/main/resources/application.yml
api/src/main/resources/data.sql

- DB Initialization 
- Added data.sql to initialize the DB with some default data e.g. administrator user
- Change the db schema to create-drop for development

<feat: api added init data; db schema changed to create-drop>

---

api/src/main/java/com/aguri/captionlive/DTO/ProjectCreateRequest.java
api/src/main/java/com/aguri/captionlive/controller/ProjectController.java
api/src/main/java/com/aguri/captionlive/model/Project.java
api/src/main/java/com/aguri/captionlive/model/Segment.java
api/src/main/java/com/aguri/captionlive/model/Task.java
api/src/main/java/com/aguri/captionlive/service/FileRecordService.java
api/src/main/java/com/aguri/captionlive/service/ProjectService.java
api/src/main/java/com/aguri/captionlive/service/impl/FileRecordServiceImpl.java
api/src/main/java/com/aguri/captionlive/service/impl/OrganizationServiceImpl.java
api/src/main/java/com/aguri/captionlive/service/impl/ProjectServiceImpl.java
api/src/main/java/com/aguri/captionlive/service/impl/TaskServiceImpl.java
api/src/main/java/com/aguri/captionlive/service/impl/UserServiceImpl.java

<feat: create project>

---

api/src/main/java/com/aguri/captionlive/DTO/ProjectCreateRequest.java
api/src/main/java/com/aguri/captionlive/DTO/UserCreateRequest.java
api/src/main/java/com/aguri/captionlive/controller/FileController.java
api/src/main/java/com/aguri/captionlive/controller/OrganizationController.java
api/src/main/java/com/aguri/captionlive/controller/ProjectController.java
api/src/main/java/com/aguri/captionlive/controller/TaskController.java
api/src/main/java/com/aguri/captionlive/controller/UserController.java
api/src/main/java/com/aguri/captionlive/model/Project.java
api/src/main/java/com/aguri/captionlive/model/Segment.java
api/src/main/java/com/aguri/captionlive/model/Task.java
api/src/main/java/com/aguri/captionlive/model/User.java
api/src/main/java/com/aguri/captionlive/service/FileRecordService.java
api/src/main/java/com/aguri/captionlive/service/OrganizationService.java
api/src/main/java/com/aguri/captionlive/service/ProjectService.java
api/src/main/java/com/aguri/captionlive/service/TaskService.java
api/src/main/java/com/aguri/captionlive/service/UserService.java
api/src/main/java/com/aguri/captionlive/service/impl/FileRecordServiceImpl.java
api/src/main/java/com/aguri/captionlive/service/impl/OrganizationServiceImpl.java
api/src/main/java/com/aguri/captionlive/service/impl/ProjectServiceImpl.java
api/src/main/java/com/aguri/captionlive/service/impl/TaskServiceImpl.java
api/src/main/java/com/aguri/captionlive/service/impl/UserServiceImpl.java
api/src/main/resources/data.sql

- rewrite file service
- drop old avatar service code 
- rewrite create user to update new file service

Feature/no ref/file service rewrite

---

api/src/main/java/com/aguri/captionlive/common/exception/GlobalExceptionHandler.java
api/src/main/java/com/aguri/captionlive/controller/AuthController.java
api/src/main/java/com/aguri/captionlive/model/User.java

- Login path
- Login status code when user not found

<chore: unify resp>

---

frontend/src/App.css
frontend/src/components/User/SignIn.js
frontend/src/pages/AllOrganizations/AllOrganizations.js
frontend/src/pages/MyOrganizations/Projects.js
frontend/src/redux/store.js
frontend/src/services/auth.js
frontend/src/services/user.js

- Frontend Sign In
- Added Sign In UI
- Still working on the sign in logic

Feature/no ref/frontend sign in page

---

frontend/src/components/User/SignIn.js
frontend/src/services/auth.js

- Frontend Sign I
- Added Sign In API
- Still working on saving into local storage

feat: frontend added signin api

---

api/src/main/java/com/aguri/captionlive/DTO/ProjectCreateRequest.java
api/src/main/java/com/aguri/captionlive/DTO/ProjectInfo.java
api/src/main/java/com/aguri/captionlive/controller/ProjectController.java
api/src/main/java/com/aguri/captionlive/controller/RemarkController.java
api/src/main/java/com/aguri/captionlive/model/Project.java
api/src/main/java/com/aguri/captionlive/model/Remark.java
api/src/main/java/com/aguri/captionlive/model/Segment.java
api/src/main/java/com/aguri/captionlive/model/Task.java
api/src/main/java/com/aguri/captionlive/repository/RemarkRepository.java
api/src/main/java/com/aguri/captionlive/service/RemarkService.java
api/src/main/java/com/aguri/captionlive/service/impl/OrganizationServiceImpl.java
api/src/main/java/com/aguri/captionlive/service/impl/ProjectServiceImpl.java
api/src/main/java/com/aguri/captionlive/service/impl/RemarkServiceImpl.java

- new feature : remark
- new feature request;
- createProject with remark

Feature/no ref/remark table

---

api/pom.xml
api/src/main/java/com/aguri/captionlive/common/JwtTokenProvider.java
api/src/main/java/com/aguri/captionlive/controller/AuthController.java

add sign up

---

frontend/src/redux/userSlice.js

- Frontend SignIn
- Now Saves User Info into local storage

feat: frontend login save user info into local storage

---

frontend/src/App.css
frontend/src/components/User/SignUp.js
frontend/src/pages/AllOrganizations/AllOrganizations.js
frontend/src/pages/MyHome/MyHome.js
frontend/src/redux/layoutSlice.js
frontend/src/redux/store.js
frontend/src/redux/userSlice.js

- Frontend SignIn and SignUp Page
- Added SignUp Page
- Added logic when interchanging between SignIn and SignUp Page

feat: frontend added complete Sign Up and Sign In Page

---

frontend/src/App.css
frontend/src/components/InfoCard/EntityInfo.js
frontend/src/components/Layout/Header/Header.js
frontend/src/components/User/SignIn.js
frontend/src/components/User/SignInUpContainer.js
frontend/src/components/User/SignUp.js
frontend/src/pages/AllOrganizations/AllOrganizations.js
frontend/src/pages/Mail/AllMails.js
frontend/src/pages/Mail/SentMails.js
frontend/src/pages/Mail/UnreadMails.js
frontend/src/pages/MyHome/MyHome.js
frontend/src/pages/MyProjects/AccessibleProjects.js
frontend/src/pages/MyProjects/AllProjects.js
frontend/src/pages/MyProjects/CommittedProjects.js

- Frontend SignIn and SignUp Page
- Frontend MyHome Page
- Refactorized Frontend SignIn and SignUp Code
- Added UI for MyHome Page

feat: refactorize sign in up code; MyHome ui

---

docker-compose/README.md
docker-compose/docker-compose-fe-dev.yml
frontend/src/App.css
frontend/src/components/InfoCard/EntityInfo.js
frontend/src/components/Layout/Header/Header.js
frontend/src/components/User/SignIn.js
frontend/src/components/User/SignUp.js
frontend/src/pages/MyHome/MyHome.js
frontend/src/redux/layoutSlice.js

- Frontend MyHome
- Completed UI for MyHome
- Updated docker-compose file for better frontend development

feat: frontend completed MyHome UI; docker-compose file for frontend

---

api/src/main/resources/data.sql

- Better Init Database for Testing
- Added membership relationships to the Init DB

chore: api added membership to the init data

---

api/src/main/java/com/aguri/captionlive/model/Access.java
api/src/main/java/com/aguri/captionlive/model/FileRecord.java
api/src/main/java/com/aguri/captionlive/model/Organization.java
api/src/main/java/com/aguri/captionlive/model/Project.java
api/src/main/java/com/aguri/captionlive/model/Remark.java
api/src/main/java/com/aguri/captionlive/model/Segment.java
api/src/main/java/com/aguri/captionlive/model/Task.java
api/src/main/java/com/aguri/captionlive/model/User.java

- frontend need the updatedTime and createdTime

<feat: add timestamp for all resp>

---

api/src/main/java/com/aguri/captionlive/DTO/UserRequest.java
api/src/main/java/com/aguri/captionlive/common/exception/GlobalExceptionHandler.java
api/src/main/java/com/aguri/captionlive/controller/AuthController.java
api/src/main/java/com/aguri/captionlive/controller/UserController.java
api/src/main/java/com/aguri/captionlive/model/User.java
api/src/main/java/com/aguri/captionlive/service/UserService.java
api/src/main/java/com/aguri/captionlive/service/impl/UserServiceImpl.java

- error when update with avatar_id

<fix: update user with cover_avatar error>

---

frontend/package.json
frontend/src/App.css
frontend/src/components/Layout/Modal/FileUpload.js
frontend/src/redux/store.js
frontend/src/services/file.js

- Frontend Upload File
- Upload File by RTK Query and React-dropzone

Feature/no ref/frontend upload file

---

api/src/main/resources/data.sql

- Better Init Database for Testing
- Renaming using Chinese

chore: api rename init database

---

api/src/main/java/com/aguri/captionlive/service/impl/UserServiceImpl.java

- update error
- check username only if the username change

<fix: check username only if the username change>

---

api/src/main/java/com/aguri/captionlive/service/impl/UserServiceImpl.java

- request error when avatarId is 0

<feat: avatar id == 0 means no avatar>

---

frontend/src/App.css
frontend/src/components/InfoCard/Avatar.js
frontend/src/components/InfoCard/EntityInfo.js
frontend/src/components/Layout/Header/Header.js
frontend/src/components/Layout/Modal/FileUpload.js
frontend/src/services/user.js

- Frontend MyHome
- Added Modify User Description

feat: frontend MyHome added modify description

---

frontend/src/components/InfoCard/Avatar.js
frontend/src/components/InfoCard/EntityInfo.js
frontend/src/components/Layout/Modal/FileUpload.js
frontend/src/services/file.js
frontend/src/services/user.js

- Frontend MyHome
- Added Upload User Avatar

feat: frontend MyHome upload avatar

---

frontend/src/App.js
frontend/src/components/Layout/Sidebar/Sidebar.css
frontend/src/components/Layout/Sidebar/Sidebar.js
frontend/src/components/Layout/Sidebar/SidebarElement.js
frontend/src/components/Layout/Sidebar/Sidebarlvl2.css
frontend/src/components/Layout/Sidebar/Sidebarlvl2.js
frontend/src/redux/layoutSlice.js

* fix route for side bar
* change style for side bar level 2

Feature/no ref/frontend myorgnization list

---

frontend/src/App.css
frontend/src/components/Layout/Sidebar/Sidebarlvl2.css
frontend/src/pages/MyOrganizations/AboutOrganization.js
frontend/src/pages/MyOrganizations/Glossaries.js
frontend/src/pages/MyOrganizations/Projects.js

- Better UI for the MyOrg Page
- Adjusted UI for MyOrg Page

chore: frontend MyOrg changed UI

---

.github/workflows/docker-build-api.yml
api/DockerFile

- GitHub Action API fails!
- API Dockerfile Maven Version upgraded to v3.9.2

bugfix: update GitHub Action

---

api/src/main/java/com/aguri/captionlive/DTO/ProjectInfo.java
api/src/main/java/com/aguri/captionlive/common/util/FileRecordUtil.java
api/src/main/java/com/aguri/captionlive/controller/OrganizationController.java
api/src/main/java/com/aguri/captionlive/controller/ProjectController.java
api/src/main/java/com/aguri/captionlive/controller/RemarkController.java
api/src/main/java/com/aguri/captionlive/controller/SegmentController.java
api/src/main/java/com/aguri/captionlive/controller/TaskController.java
api/src/main/java/com/aguri/captionlive/controller/UserController.java
api/src/main/java/com/aguri/captionlive/model/FileRecord.java
api/src/main/java/com/aguri/captionlive/model/Project.java
api/src/main/java/com/aguri/captionlive/service/ProjectService.java
api/src/main/java/com/aguri/captionlive/service/RemarkService.java
api/src/main/java/com/aguri/captionlive/service/TaskService.java
api/src/main/java/com/aguri/captionlive/service/UserService.java
api/src/main/java/com/aguri/captionlive/service/impl/OrganizationServiceImpl.java
api/src/main/java/com/aguri/captionlive/service/impl/ProjectServiceImpl.java
api/src/main/java/com/aguri/captionlive/service/impl/RemarkServiceImpl.java
api/src/main/java/com/aguri/captionlive/service/impl/TaskServiceImpl.java
api/src/main/java/com/aguri/captionlive/service/impl/UserServiceImpl.java

- Code format
- Comment out useless functions
- Add new feature: upload taskFile.

<chore: code format>

---

api/src/main/java/com/aguri/captionlive/DTO/ProjectInfo.java

<fix: missing task type>

---

api/src/main/resources/data.sql

- Frontend: MyOrg -> Glossary
- Added init glossary data

chore: api added init glossary data

---

api/src/main/java/com/aguri/captionlive/service/impl/TaskServiceImpl.java

- withdrawal commit need clear user

<fix: withdrawal commit need clear user>

---

api/src/main/java/com/aguri/captionlive/DTO/ProjectInfo.java

- projectInfo: add cover file record id

<fix: add cover file record id>

---

api/src/main/java/com/aguri/captionlive/DTO/ProjectRequest.java
api/src/main/java/com/aguri/captionlive/controller/UserController.java
api/src/main/java/com/aguri/captionlive/service/impl/FileRecordServiceImpl.java
api/src/main/java/com/aguri/captionlive/service/impl/ProjectServiceImpl.java

- create project with task source complete
- application.yml file separator generated by system
- remove meaningless console output

Bugfix/no ref/bugs

---

frontend/src/App.css
frontend/src/components/InfoCard/Avatar.js
frontend/src/components/InfoCard/EntityInfo.js
frontend/src/components/Layout/Header/Header.js
frontend/src/components/Layout/Modal/FileUploader.js
frontend/src/components/Project/Worksheet.js
frontend/src/pages/MyOrganizations/Projects.js
frontend/src/redux/store.js
frontend/src/services/project.js
frontend/src/utils/segment.js

- frontend worksheet/project
- Finished UI for Page Worksheet
- Allowed uploading cover file for a worksheet

feat: frontend worksheet ui; upload cover

---

frontend/src/App.css
frontend/src/assets/workflows.js
frontend/src/components/Project/AddSegment.js
frontend/src/components/Project/Segment.js
frontend/src/components/Project/Worksheet.js
frontend/src/pages/MyHome/MyHome.js
frontend/src/pages/MyOrganizations/Projects.js
frontend/src/redux/layoutSlice.js
frontend/src/services/organization.js
frontend/src/utils/segment.js

- Frontend Edit Worksheet
- Enable Create Segment
- Enable Delete Segment

feat: Frontend Edit Worksheet

---

api/src/main/resources/data.sql

- Need Super User
- Added Super User

chore: api added super user

---

api/src/main/java/com/aguri/captionlive/model/Membership.java
api/src/main/java/com/aguri/captionlive/repository/MembershipRepository.java
api/src/main/java/com/aguri/captionlive/service/impl/MembershipServiceImpl.java

- misunderstanding the property : 'position'

<fix: add new property 'leaderIds' in get organization by id resp>

---

api/src/main/java/com/aguri/captionlive/model/Organization.java
api/src/main/resources/data.sql

- Misconfigured table relationship：user and organization，organization and project

<fix: typo foreign key>

---

frontend/src/components/Organization/AddOrganization.js
frontend/src/pages/AllOrganizations/AllOrganizations.js
frontend/src/services/organization.js

- Frontend Create Org
- Added Frontend Create Org 
- Added Header With Auth Info For Org Service API

Feat/no ref/add org

---

frontend/src/components/User/SignIn.js
frontend/src/components/User/SignUp.js

* Password will be encrypted using sha256, the backend will only recieve encrypted password.
* password text will not show on input box, will show '*' instead

Feature/no ref/frontend encrypt password

---

frontend/package.json

add sha256

---

api/src/main/resources/data.sql

- Updated Init Data Password According To SHA256 Encryption

chore: updated password

---

frontend/src/App.js
frontend/src/assets/sidebar.js
frontend/src/components/Layout/Sidebar/Sidebar.js
frontend/src/components/Layout/Sidebar/Sidebarlvl2.js
frontend/src/pages/Mail/AllMails.js
frontend/src/pages/Mail/SentMails.js
frontend/src/pages/Mail/UnreadMails.js
frontend/src/pages/MyOrganizations/AboutOrganization.js
frontend/src/pages/MyOrganizations/Glossaries.js
frontend/src/pages/MyOrganizations/Projects.js
frontend/src/pages/MyProjects/AccessibleProjects.js
frontend/src/pages/MyProjects/AllProjects.js
frontend/src/pages/MyProjects/CommittedProjects.js

Chore/no ref/frontend sidebarlv2 general

---

frontend/src/components/InfoCard/Avatar.js
frontend/src/components/Layout/Sidebar/Sidebarlvl2.css
frontend/src/components/Project/Segment.js
frontend/src/config/config.js
frontend/src/services/auth.js
frontend/src/services/file.js
frontend/src/services/organization.js
frontend/src/services/project.js
frontend/src/services/request.js
frontend/src/services/user.js

- Frontend config file for hostname
- Added config file setting Hostname to 13.59.233.173

chore: frontend added config file for host name; modified sidebarl2

---

docker-compose/docker-compose-fe-dev.yml
docker-compose/docker-compose.yml
frontend/DockerFile
frontend/src/config/config.js

chore: configure DNS

---

frontend/src/App.css
frontend/src/components/InfoCard/EntityInfo.js
frontend/src/components/InfoCard/UserInfo.js
frontend/src/components/Project/Segment.js
frontend/src/components/User/SignUp.js
frontend/src/pages/MyHome/MyHome.js
frontend/src/utils/segment.js
frontend/src/utils/time.js

- Frontend Nickname
- Added Frontend Nickname
- Fixed Start & End Time Error

feat: frontend nickname

---

api/src/main/java/com/aguri/captionlive/service/impl/RequestServiceImpl.java

- This function does not work becase I did not delete test code

<fix: delete useless code>

---

frontend/src/App.css
frontend/src/components/Layout/Sidebar/Sidebar.js
frontend/src/components/Project/ShareProject.js
frontend/src/components/Project/Worksheet.js
frontend/src/redux/layoutSlice.js
frontend/src/services/organization.js

- Frontend Share Project to User
- Shares Users
- Frontend Share Project to Organization
- Shares Organizations

feature: frontend basic share project

---

api/src/main/java/com/aguri/captionlive/common/filter/JwtAuthenticationFilter.java

- Rewrite the code of the filter.
- Token verification is enabled, it only verifies the legitimacy of the token

<feat: rewrite jwt filter>

---

docker-compose/docker-compose-dev.yml
docker-compose/docker-compose-fe-dev.yml
docker-compose/docker-compose-prod.yml

- Mount app/files in the api container to the outside environment

hotfix: docker file mnt

---

frontend/src/api/organization.js
frontend/src/api/project.js
frontend/src/api/request.js
frontend/src/api/user.js
frontend/src/components/InfoCard/Avatar.js
frontend/src/components/InfoCard/UserInfo.js
frontend/src/components/Layout/Header/Header.js
frontend/src/components/User/SignUp.js
frontend/src/config/config.js
frontend/src/pages/AllOrganizations/AllOrganizations.js
frontend/src/pages/Mail/AllMails.js
frontend/src/pages/MyOrganizations/AboutOrganization.js
frontend/src/pages/MyOrganizations/Projects.js
frontend/src/pages/MyProjects/AccessibleProjects.js
frontend/src/redux/layoutSlice.js
frontend/src/services/auth.js

- Frontend API Check Error and Change to Login Page

Chore/no ref/frontend api filter

---

frontend/src/App.css
frontend/src/assets/workflows.js
frontend/src/components/Project/Worksheet.js

- Better UI for Worksheet
- Button to Copy Staff List

<Chore: Push to Production v1.0.1>

---

frontend/src/App.css
frontend/src/assets/workflows.js
frontend/src/components/Project/Worksheet.js

- Better UI for Worksheet
- Button to Copy Staff List

Feature/no ref/prod/button copy staff

---

frontend/src/components/InfoCard/Avatar.js
frontend/src/components/Layout/Sidebar/Sidebar.css
frontend/src/utils/lazyimage.js

* sidebar now will fix on the right hand side
* image can now be loaded with credentials

fix sidebar position, fix image loading

---

frontend/src/components/Project/Segment.js

* fixed downloading with credentials

fix downloading with credentials

---

frontend/src/App.css
frontend/src/pages/AllOrganizations/AllOrganizations.js
frontend/src/pages/MyOrganizations/AboutOrganization.js
frontend/src/pages/MyOrganizations/Glossaries.js
frontend/src/pages/MyOrganizations/Projects.js
frontend/src/pages/MyProjects/AccessibleProjects.js
frontend/src/pages/MyProjects/CommittedProjects.js

- Allowing Search for Projects and Organizations

feat: frontend search for projects and organization

---

api/src/main/java/com/aguri/captionlive/controller/ProjectController.java
api/src/main/java/com/aguri/captionlive/service/ProjectService.java
api/src/main/java/com/aguri/captionlive/service/impl/ProjectServiceImpl.java
api/src/main/java/com/aguri/captionlive/service/impl/UserServiceImpl.java

- Now, the users accessible to the project are jointly maintained through the access table and the ownership table

 shared user was found by ownership and access

---

frontend/src/components/Glossary/GlossariesTable.js
frontend/src/components/Layout/Sidebar/Sidebar.css
frontend/src/components/Layout/Sidebar/Sidebar.js
frontend/src/services/glossary.js

* add glossary delete function
* fix sidebar toggle style (now align to the center)

fix sidebar toggle, add glossary delete

---

frontend/src/components/InfoCard/Confirm.js
frontend/src/components/Project/Segment.js
frontend/src/components/Project/Worksheet.js

- Frontend Added Prompt When Deleting a Project or Segment

Feat/no ref/fronent confirm delete
